### ISSUE TITLE
Fingerprint verification dialog should cover the bottom navigation - Android

### ISSUE THREAD

**Issue by imdominic** [LiskHQ/lisk-mobile#1023]
- The bottom navigation stands on top of the dialog.

![Screenshot_20200123-095433_Lisk](https://user-images.githubusercontent.com/45934100/72974067-b3f5a900-3dce-11ea-8cce-7d9d1256ee90.jpg)

### Steps to reproduce

- Log into the wallet -> Click on a transaction
- Log into the wallet -> Navigate to settings -> Enable or Disable fingerprint sensor

**Comment by ManuGowda** [comment]
The issue is valid, but it is of lower priority, we can keep this for later releases.

**Comment by ManuGowda** [comment]
This bug is invalid with latest v3 release
