### ISSUE TITLE
Wallet balance amounts always hide on ver 1.4.0

### ISSUE THREAD

**Issue by hitobb** [LiskHQ/lisk-mobile#1052]
### Expected behavior

Wallet balance amounts always hide on ver 1.4.0

### Actual behavior

Lisk balance amounts should be always checked on ver 1.4.0

### Steps to reproduce

- Discreet mode off (Default)
![_20200928_155106](https://user-images.githubusercontent.com/14948578/94399971-4f7fba80-01a3-11eb-829e-ba7ee19102b4.JPG)

![_20200928_155131](https://user-images.githubusercontent.com/14948578/94399985-5a3a4f80-01a3-11eb-933a-dc97d7006672.JPG)

- Discreet mode on

![_20200928_155153](https://user-images.githubusercontent.com/14948578/94400016-658d7b00-01a3-11eb-9e83-ff3b4f53fa3c.JPG)

![_20200928_155217](https://user-images.githubusercontent.com/14948578/94400045-6e7e4c80-01a3-11eb-8517-497607ff15df.JPG)

### Which version(s) does this affect? (Environment, OS, etc...)

From Ver 1.4.0
Android Version 9

**Comment by Yurchezz** [comment]
Did you find a solution to this issue? Cause I cloned this repository and seems to work fine when running via emulator but when I downloaded it from App Store amount of coins always hidden

**Comment by ejfrancis** [comment]
Yeah I see this same behavior on Android

**Comment by renekorss** [comment]
Having same issue on iOS.

**Comment by reyraa** [comment]
Thanks for reporting this issue. It's not included in 1.4.1.
