### ISSUE TITLE
Issue while running "npm run build:android" 

### ISSUE THREAD

**Issue by Yurchezz** [LiskHQ/lisk-mobile#1053]
### Expected behavior
     Finish building project and running the emulator with app
### Actual behavior
   error ENOTDIR invalid cwd C:\Users\{Path}\lisk-mobile\node_modules\react-native-interactable\android. Run CLI with --verbose flag for more details.
    
    error and log similar to the issue on stackoverflow
    https://stackoverflow.com/questions/59891780/error-enotdir-invalid-cwd-react-native-interactable

    I also tried https://github.com/wix/react-native-interactable/issues/230 but it won't help
### Steps to reproduce
      I was following the readme file

      git clone < project repository >   //development
      cd list-mobile
      npm install
      npm run build:android
       
### Which version(s) does this affect? (Environment, OS, etc...)
     Windows 10, Powershell

**Comment by ManuGowda** [comment]
You can use `npm run release:android` this will do the same job.
