### ISSUE TITLE
Update Send LSK Design

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1138]
### Description
Align components of send flow to match proposed design

### Motivation
Improve user experience

### Additional Information
- Implemented design should match proposed design
- Add Bookmark button should navigate to Add Bookmark screen with pre-filled address
![Screenshot 2021-11-18 at 12 43 50](https://user-images.githubusercontent.com/28750984/142409432-bfd75ca4-4ef9-4704-9c68-f8a543144362.png)

**Comment by ManuGowda** [comment]
@Balanced02 the transaction summary screen is not updated, it still shows the old screen

New screen for transaction summary
![image](https://user-images.githubusercontent.com/6449871/143774746-17d3170e-3223-4958-957b-9bc61fc1ea82.png)
