### ISSUE TITLE
Biometric Passphrase not matching design

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1175]
### Expected behavior
The Passphrase screen on disabling biometrics should match design

### Steps to reproduce
- Login to the app
- Go to settings and try disabling the Biometrics
<img width="370" alt="Screenshot 2021-12-16 at 17 38 37" src="https://user-images.githubusercontent.com/28750984/146412036-4d19cb03-dabf-4282-a6a4-04f8f4240ac1.png">

### Which version(s) does this affect? (Environment, OS, etc...)
Android & iOS v2.0.0

**Comment by ManuGowda** [comment]
This issue is similar to #1180  and #1185
