### ISSUE TITLE
BigInt not supported in Android production builds

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1176]
### Expected behavior
Should support BigInt conversions on Android production build

### Actual behavior
- Does not support BigInt and the Lisk Core throws error when trying to sign transactions

### Steps to reproduce
- Either generate a production build, or run the application without debug mode
- Try sending LSK
- On the overview screen, click Send
- The app just hangs there without showing any error message (using the console, you can check the real error message)

### Which version(s) does this affect? (Environment, OS, etc...)
v2.0.0 (android production build)

**Comment by ManuGowda** [comment]
We haven't be able to resolve the android issue. However, we can resolve this issue by patching `signTransaction` function to ignore the validation, which is what causing the error.

Once react-native has some resolution for `BigInt` we will update signTransaction function. Until then we will use the patched version of `signTransaction`.
