### ISSUE TITLE
Transaction history only up 10 transactions

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-mobile#1179]
### Expected behavior
The transaction history should show all the txs (with a load more button or smth similar)
### Actual behavior
Transaction history shows only up 10 latest transactions
### Steps to reproduce
Log in to an account that has more then 10 transactions, check the transaction history.
### Which version(s) does this affect? (Environment, OS, etc...)
iOS 15, lisk mobile 2.0.0

**Comment by ManuGowda** [comment]
@przemerr for feature rich experience users can use Lisk Desktop? however, we will consider your opinion and discuss if we can increate the list of transactions to more than 10. Thanks for request 👍🏼  

@reyraa @ann-vashchenko let's discuss this request and come to a resolution.
