### ISSUE TITLE
Visual issues discovered in v2.0.0-beta.0

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#1180]
I've detected the following issues in Lisk Mobile v2.0.0-beta.0

### Missing margin from the top 
The top margin is missing in the sign in screen as well as the send screen

![top-margin-1](https://user-images.githubusercontent.com/666685/146442051-ae7e661b-2319-4be8-9255-cffc3e27f8c4.PNG)
![top-margin-2](https://user-images.githubusercontent.com/666685/146442056-293e5571-89f4-4517-be96-1f6effdda21e.PNG)

### Small touch zone
The touch zone of the locked balance is only around the arrow, it should be around the number, unit and the arrow to make it easier to touch. 

![hot-zone-too-small](https://user-images.githubusercontent.com/666685/146442727-378a5a3e-8c4b-4c80-b6a9-818e564ce9af.PNG)

Although I have created only one screenshot, this issue exist on all arrow buttons including the screen back buttons. The arrow buttons need a padding of about 15px - 20px, increasing the touch area to a minimum of 50px x 50px. 

### Unnecessary space
There's an unnecessary space between the button and the keyboard in the send page

![unwanted-space](https://user-images.githubusercontent.com/666685/146443234-a25d84dc-585e-477c-9d45-77735e2ca296.PNG)

### Missing horizontal padding
The horizontal padding is missing in the send screen.

![horizontal-padding](https://user-images.githubusercontent.com/666685/146443529-14328d5c-be2d-47aa-ac76-8c8f54f45788.PNG)

### Extra margin bottom
Either the height of the bottom tab bar is too big, or there's an unwanted margin between the bottom tab bar and the bottom most part of the scroll view.

![extra-space-botton](https://user-images.githubusercontent.com/666685/146446436-1b2da79d-d3ed-4f63-b34f-a6d6a82e9265.PNG)

### List item details
I noticed two issues with the list items:
- The height of each item.
- The number of characters before and after the ellipsis.

![wrong-item-height-1](https://user-images.githubusercontent.com/666685/146447060-749b628b-6cfe-49d3-b028-b0c1089d5331.PNG)
![wrong-item-height-2](https://user-images.githubusercontent.com/666685/146447064-fc465975-1c56-4339-89af-5570173a1fb7.PNG)

### Logo is cut
When you scroll the home page, the Lisk logo is cut. It seems like the logo is restricted in a parent view which hides the top part of it.

![logo-is-cut](https://user-images.githubusercontent.com/666685/146450274-a5d63c65-272d-4e50-8cce-c8a7e17724e3.PNG)

### The stretching view
This issue occurs in two views: A. Disable/enable biometric authentication. B. Backup passphrase. The view stretches all the way to the bottom and doesn't align with the original design.

### Avatar overlaps while scrolling 

![Image from iOS](https://user-images.githubusercontent.com/61688877/147758551-3c08b6df-5917-4289-b44f-85d67ea6a210.jpg)

### Avatars on the transaction details screen should be aligned to the right end of the border 
![Image from iOS (1)](https://user-images.githubusercontent.com/61688877/147758605-34ad31b2-170b-4807-8c14-efa0cbfde282.jpg)

### T
![Image from iOS](https://user-images.githubusercontent.com/61688877/147758650-507a862b-b545-4101-bde7-eea824c369d2.png)
here is still the bookmark illustration on the first step of the send transaction flow.

### Expected design:

![Screenshot 2021-12-30 at 17 22 58](https://user-images.githubusercontent.com/28750984/147769751-adbee031-04ee-4328-9cf3-fce660c772e1.png)

**Comment by ManuGowda** [comment]
@Balanced02 there are several send screen issues which can be addressed with new design.
Please adopt the below design changes 🙏🏼 

<img width="320" alt="Screenshot 2021-12-31 at 4 45 54 PM" src="https://user-images.githubusercontent.com/6449871/147831096-c33b8356-73e0-4323-b444-319df870a640.png">
dan

<img width="326" alt="Screenshot 2021-12-31 at 4 45 39 PM" src="https://user-images.githubusercontent.com/6449871/147831094-bcf467a8-4753-46f8-8877-113379be6e19.png">

**Comment by Balanced02** [comment]
@reyraa 

I cannot replicate the space between the button and keyboard. Pls see attached screenshot and help with steps to reproduce, and if possible, the phone model you're using to test too.
![Screenshot 2022-01-04 at 12 53 41](https://user-images.githubusercontent.com/28750984/148055333-545548b7-cc37-41d4-9115-d162ca9f2fa5.png)
