### ISSUE TITLE
Tooltips exit button doesn't work

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-mobile#1186]
### Expected behavior
The `X` exit button should work
### Actual behavior
The `X` exit button doesn't work, a user has to swipe the description down to close it
### Steps to reproduce
Click the tool tips in the send screen
![IMG-2239](https://user-images.githubusercontent.com/25085095/146537906-56f543dd-aa72-4266-8c95-b9cb6c0eff42.jpg)

### Which version(s) does this affect? (Environment, OS, etc...)
iOS 15, mobile 2.0.0

**Comment by ManuGowda** [comment]
The close button worked for me. @Balanced02 the header bug needs to be fixed

**Comment by przemerr** [comment]
Yes, this is the same case, I think there was an alpha version in testflight for a bit, which had some bugs that were fixed in the beta. The `X` is clickable in the beta.
