### ISSUE TITLE
step labels are not visible. (dark theme)

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-mobile#1189]
### Expected behavior
Should look similar to the light theme.

### Actual behavior
Not visible
![image](https://user-images.githubusercontent.com/44485074/146667166-e67cbf94-9200-4d06-838d-687d4dc2e754.jpeg)

![image](https://user-images.githubusercontent.com/44485074/146667169-3d0a9d9e-add0-430b-8e56-7e7e6a7882fd.jpeg)

### Steps to reproduce
Switching themes

### Which version(s) does this affect? (Environment, OS, etc...)
iOS 15.2
v2.0.0-beta.0

**Comment by ManuGowda** [comment]
This issue will be resolve by #1180
