### ISSUE TITLE
Transfer fails for multi-signature accounts.

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-mobile#1191]
### Expected behavior
One of the following:
1. In the case of a multi-signature account, the Send tab will be disabled or display a message stating that it is disabled.

2. For the second passphrase holder, the behavior is similar to Lisk Desktop.

3. Copy the transaction string signed by the sender account. and a message indicating that further action in Lisk Desktop is required.

### Actual behavior
Failed to send translation
![image](https://user-images.githubusercontent.com/44485074/146782737-7d14dcea-7ce3-40b2-bf3b-f9d3ed4edc71.jpeg)

### Steps to reproduce
1. Sign in with your multi-signature account.
2. Send LSK

### Which version(s) does this affect? (Environment, OS, etc...)
iOS 15.2
v2.0.0-beta.0

**Comment by ManuGowda** [comment]
@Balanced02 Please adopt the multi-signature changes according to new design

<img width="1137" alt="Screenshot 2021-12-31 at 4 42 37 PM" src="https://user-images.githubusercontent.com/6449871/147830985-fcd285fc-c2d4-4b2d-bb0b-aebb4e586454.png">

<img width="1135" alt="Screenshot 2021-12-31 at 4 42 23 PM" src="https://user-images.githubusercontent.com/6449871/147830981-c1b28b4f-c16d-4cba-89c1-24206be0a711.png">
