### ISSUE TITLE
A very small amount can be sent.

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-mobile#1193]
### Expected behavior
If there are 9 decimal places, an error message is displayed.

### Actual behavior
We can send it.
![image](https://user-images.githubusercontent.com/44485074/146890544-c1914558-0299-47c2-8031-cb5e4c62fef3.jpeg)
https://testnet-service.lisk.com/api/v2/transactions?senderAddress=lskmw4oyhawvk9us5cm45jep7gx65b86p4mm8ubfz&height=15266832

### Steps to reproduce
1. Enter the amount up to 9 decimal places in the Amount field
2. Tap the Continue button.

### Which version(s) does this affect? (Environment, OS, etc...)
iOS 15.2
v2.0.0-beta.0

**Comment by ManuGowda** [comment]
Thank you for reporting, the minimum possible up to 8 decimal places, please read the following for few more information. https://github.com/LiskHQ/lips/blob/9eac23f41348d23eebf724f119f8d988e36cacfe/proposals/lip-0013.md#appendix

**Comment by przemerr** [comment]
Not sure if you understood the issue @ManuGowda , the wallet allows you to send amounts lower than 10^-8, it will round them up to 0 and send it as 0 LSK, try sending 0.00000000000000000000001 for example. Unless it's an expected behaviour.
