### ISSUE TITLE
Show bookmark details when user swipes

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1212]
### Description
Show details of bookmark when user swipes for more actions

Bookmark name or address should still be visible on the screen when a user swipes for more actions on a bookmark item

### Motivation
Ensures users take actions on intended item
![Screenshot 2022-01-07 at 13 01 10](https://user-images.githubusercontent.com/28750984/148541381-77c6ee2f-c8ee-4eda-810d-4aa89b048749.png)

**Comment by ManuGowda** [comment]
Duplicate of #1222
