### ISSUE TITLE
Re-focus on Send screen should reset address

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1223]
### Expected behavior
Address input on send screen should reset when a user navigates out from the screen and re-focuses

### Actual behavior
When you press SEND LSK from other account details screen, the address shows, but if the user clears the address and visits the send screen again, the address is pre-filled again

### Steps to reproduce
- Go to details of another account
- Select SEND LSK
- Address is populated on the send screen
- Clear the address
- Go to Request Tab and go back to Send Tab
- Address is filled again

### Which version(s) does this affect? (Environment, OS, etc...)
v2.0.0 android & iOS

**Comment by przemerr** [comment]
I found a bug related to the issue above, If you go to the account details of another account and click SEND LSK the recipient's address is correctly input, but if you go to a different account now and its account details page and click SEND LSK, the address of a previous recipient is shown, which may lead to unwanted transfer.

Probably when the https://github.com/LiskHQ/lisk-mobile/issues/1223 is resolved, the bug will be resolved also, but I'm posting it, so this scenario is also checked after applying the fix.
