### ISSUE TITLE
Send maximum amount wrongly calculated

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-mobile#1254]
### Expected behavior
The maximum amount should be calculated correctly
### Actual behavior
It's not, on top of that, if you want manually override it, error saying that the balance is not enough pops up.
### Steps to reproduce
Try sending entire balance using the `Send maximum amount` button. Calculate manually (the correct amount, should be `Balance - 0.05LSK - fee`)
![image](https://user-images.githubusercontent.com/25085095/151558877-93666b56-4df0-4993-b6e4-f22bff16f2a0.png)

### Which version(s) does this affect? (Environment, OS, etc...)
iOS 15 liskmobile 2.0.0-rc.1

**Comment by ManuGowda** [comment]
There is a variance of approx `0.00004LSK`, this should be resolved in next minor release.
