### ISSUE TITLE
App performace optimization and bundle size

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1269]
### Description
- Some components keeps re-rendering when not supposed to, thus, causing performance issues
- The app's bundle size is approximately 44mb on play store, we can have this reduced further. It used to be 22 mb in v2

### Motivation
- Improve smooth usage of application, thus enhancing user experience and avoid unnecessary re-renders

**Comment by ClementeSerrano** [comment]
We will be executing the following strategy:

## Profiling and Identifying Bottlenecks

1. **Profiling Tool**: 
    - Utilize Hermes Profiler to identify components and functions that are resource-heavy.
    - **Resources**: 
        - [React Native Profiling](https://reactnative.dev/docs/profile-hermes)
        - [iOS & Android Tools](https://www.callstack.com/blog/profiling-react-native-apps-with-ios-and-android-tools)   

2. **Network Requests**: 
    - Inspect and optimize all network requests, specially on applications management and token transfer modules.

4. **Initial Load Time**: 
    - Improve initial load time through code-splitting and lazy-loading.

## Optimization

1. **Optimize Hooks**: 
    - Focus on `useSendtokenForm` and other hooks causing excessive re-renders or consuming excessive resources.
    - Use `useMemo` and `useCallback` for memoization.
    - Use `React.memo` for functional components.


2. **Virtualized Lists**: 
    - Use `FlatList` or `SectionList` with proper keys and optimize the `renderItem` method.

4. **Optimize Images and Media**: 
    - Compress and lazy-load images and media files.

5. **Throttle and Debounce**: 
    - Use throttling or debouncing for events like scrolling, input changes, and window resizing.

## Code Quality

1. **Bundle Size**: 
    - Remove unused modules and codes.
    - Use `react-native-bundle-visualizer` to analyze bundle size.

2. **Code Splitting**: 
    - Implement code splitting to break down large bundles.

3. **Tree Shaking**: 
    - Enable tree shaking to eliminate dead code.

## Testing

1. **Performance Tests**: 
    - Measure key performance metrics to validate optimizations.

2. **User Testing**: 
    - Conduct user testing for performance validation.

**Comment by ClementeSerrano** [comment]
# Performance Report: React Native App Analysis

## Introduction
This report provides an in-depth analysis of the performance of our React Native app, focusing on RAM and CPU usage, as well as network and disk usage. The findings reveal several areas of concern, particularly related to memory consumption and CPU utilization. Detailed reports and evidence are attached in the comments section.

## 1. High Initial RAM Consumption
The app exhibits a high initial RAM consumption, averaging 400 MB upon startup on iOS devices. This elevated consumption could potentially affect the app’s performance and responsiveness, necessitating further investigation and optimization.

## 2. RAM Consumption Peaks
The most substantial RAM consumption occurs during the account creation and adding flows. This increase in memory usage during these specific processes requires immediate attention to enhance user experience and ensure smooth operation.

## 3. Memory Leaks and Linear RAM Usage Increase
There is a noticeable linear increase in RAM usage over time, starting at approximately 400 MB and reaching almost 700 MB within 10 minutes, even when the app is in IDLE mode. This trend indicates the presence of significant memory leaks, which are imperative to address to prevent potential app crashes and improve overall performance.

## 4. CPU Usage Spikes
The app experiences peaks of CPU usage exceeding 100% during certain operations, especially account creation/adding and token transfers. These spikes are concerning and need optimization to ensure the app’s efficiency and responsiveness. Notably, the CPU usage stabilizes to 0% during IDLE states, which is a positive aspect.

## 5. Acceptable Network and Disk Usage
On a positive note, the network and disk usage of the app remain within acceptable levels. The network usage does not exceed 100 bytes/s, and the disk usage is capped at 300 KB, which are within acceptable parameters and do not pose immediate concerns.

## Conclusion
While the app maintains acceptable levels of network and disk usage, the high initial RAM consumption, significant memory leaks, and peaks in CPU usage during specific operations are areas that need immediate attention and optimization. Addressing these issues will be crucial in improving the app’s performance, user experience, and overall stability.

## Recommendations
- Investigate and optimize the high initial RAM consumption, focusing on startup processes and initializations.
- Address the significant RAM consumption during account creation and adding flows through code optimization and memory management.
- Identify and resolve the memory leaks causing the linear increase in RAM usage over time.
- Optimize CPU usage during account creation/adding and token transfers to prevent spikes and improve app efficiency.
- Continue monitoring network and disk usage to ensure they remain within acceptable levels.

**Comment by ManuGowda** [comment]
Closing in favour of

https://github.com/LiskHQ/lisk-mobile/issues/2067
https://github.com/LiskHQ/lisk-mobile/issues/2068
https://github.com/LiskHQ/lisk-mobile/issues/2069
