### ISSUE TITLE
Update copy value of Request screen to be a launch protocol

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1315]
### Description
- If I insert amount value in request screen, the copied value is a launch protocol to the Send screen
- Users should be able to use the launch protocol correctly by Lisk Mobile
- Users should be able to use the launch protocol correctly by Lisk Desktop

### Motivation
This is to enable users send a url (launch protocol) to request LSK

**Comment by reyraa** [comment]
The copy icon next to the address should copy the address, and the QA code should:

 - Represent the address is no amount is inserted.
 - Represent a launch protocol if an amount value is given.
 
 Therefore the current implementation matches the desired UX.
 
 I'll close this issue as invalid.
