### ISSUE TITLE
Update Terms and Condition

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1317]
### Expected behavior
Update link to Terms and Condition on Walkthrough screen to be https://lisk.com/terms-conditions

### Actual behavior
Terms and condition forwards to an outdated Lisk [Mobile Privacy Policy](https://lisk.com/privacy-policy-mobile) and not the Terms and Conditions

### Steps to reproduce
<img width="275" alt="image" src="https://user-images.githubusercontent.com/28750984/159761301-e513fc92-8f4c-499f-8c1e-85abdf1d5d32.png">

Click on Terms and Condition from this screen

### Which version(s) does this affect? (Environment, OS, etc...)
v2.0.0

**Comment by ClementeSerrano** [comment]
Issue solved on https://github.com/LiskHQ/lisk-mobile/pull/1408
