### ISSUE TITLE
Update Terms and Condition and Add Privacy Policy to settings

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1318]
<img width="240" alt="image" src="https://user-images.githubusercontent.com/28750984/159763777-3d618684-1688-4fe2-83fc-405c89982bf4.png">

- Update Terms and Condition link to forward to https://lisk.com/terms-conditions
- Add Privacy Policy menu to settings and it should redirect to https://lisk.com/privacy

### Which version(s) does this affect? (Environment, OS, etc...)
- v2.1.1

**Comment by ClementeSerrano** [comment]
Issue solved on https://github.com/LiskHQ/lisk-mobile/pull/1408
