### ISSUE TITLE
Remove application from blockchain management flow 

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-mobile#1392]
### Description
User can remove an application from the local storage by visiting application management
User can not remove the default application provided by lisk foundation
In case user remove the current application it should be navigate to lisk application	

### Acceptance Criteria
**Step 1:** Allow user to review the application details Ask for confirmation 
   - Allow users to show application details such as Application name, avatar, owner address, 
   application status, chainId. Last update, Last Certificate Height, deposit, application URL, custom 
   background
**Step 2:** Show user the success page and back to the wallet`
- Check for the isDefault application to avoid default application remove required design
- Ensure UI/UX design requirements are met
- Add required unit tests
- Add required new e2e tests
	
### Additional Information

- Use the ‘useApplicationsManagement’ hook to remove the application
- Suggestion component name `RemoveApplicationFlow`
- Suggestion component name `RemoveApplicationSuccess`
- Suggestion component name `RemoveApplicationDetails`

**Comment by ClementeSerrano** [comment]
PR merged
