### ISSUE TITLE
Failed to encrypt account using argon2 

### ISSUE THREAD

**Issue by ClementeSerrano** [LiskHQ/lisk-mobile#1462]
### Expected behavior

When setting up a device password or trying to create an account, I should be able to encrypt and proceed successfully to the account creation.

### Actual behavior
On Android Simulators, the process fails giving the following error:

```
{
  error: [
    Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
  ]
}
```

The error occurs on 2 places of the app:

1. Secret recovery phrase: 
<img width="436" alt="Screenshot 2022-08-26 at 17 17 12" src="https://user-images.githubusercontent.com/9727036/186937722-0c96d0e8-f374-40a3-9bd1-144dc0ac24ba.png">

2. Create account button click (app breaks here):
<img width="436" alt="Screenshot 2022-08-26 at 17 30 22" src="https://user-images.githubusercontent.com/9727036/186940365-28d131b6-ea35-44fa-bfb5-f69740d98053.png">

On iOS Simulator works perfectly.

### Steps to reproduce
1. Run the app on Android device (`npm run android`). Make sure you follow all the install & setup instructions from the `README`.
2. Go to the *Manage accounts* screen.
3. Click on *Create it now* label button, or  *Secret recovery phrase* button.
4. Enter recovery phrase and click on *Continue*.
5. Enter passwords and username (meeting password requirements). Tested with password `Password1!`.
6. Agree on terms and conditions toggle.
7. Click on *Save account*
8. You will see an error toast.

Tested on:

- Processor: Apple M1 Pro
- OS: macOS Monterrey 12.4.
- Simulator: Android Studio Chipmunk | 2021.2.1 Patch 2
  - Runtime version: 11.0.12+0-b1504.28-7817840 aarch64
  - VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  - GC: G1 Young Generation, G1 Old Generation
  - Memory: 1280M
  - Cores: 10
  - Registry: external.system.auto.import.disabled=true

### Which version(s) does this affect? (Environment, OS, etc...)
Development, Android.

**Comment by ManuGowda** [comment]
This issue was resolved https://github.com/LiskHQ/lisk-mobile/pull/1911
