### ISSUE TITLE
Hide "View all" button on "Transactions Summary" when user has no transactions

### ISSUE THREAD

**Issue by ClementeSerrano** [LiskHQ/lisk-mobile#1573]
### Expected behavior
If user has no transactions on his account, the "_View all_" button that redirects to the _Transaction List_ on the _Home_ screen should be hidden.

### Actual behavior
The button is showing always, even if the user has no transactions yet.

![Screenshot 2022-12-29 at 16 45 00](https://user-images.githubusercontent.com/9727036/209977122-afa7da6f-f56f-473a-8038-964dad07d6fe.png)

### Steps to reproduce
1. Login to an account with no transactions.
2. Go to the _Home_ tab screen.
3. See that in the _Transaction Summary_ section, the "_View all_" button is available to press.

### Which version(s) does this affect? (Environment, OS, etc...)
All.

**Comment by ManuGowda** [comment]
@Balanced02 @ClementeSerrano please take a look at the updated design https://www.figma.com/file/jjuNNU9XxpeL57P25H1qri/Mobile-Prototype?node-id=1%3A19270&t=TtqtmBbL1AKFgLHd-4

we have implement the updated design 🙏🏼
