### ISSUE TITLE
Transaction parameters field not visible on Android

### ISSUE THREAD

**Issue by ClementeSerrano** [LiskHQ/lisk-mobile#1644]
### Expected behavior
Users should be able to access all details of a transaction.

### Actual behavior
Only for Android, the transaction _Parameters_ field don't show the "_Expand_" button, so user is not able to see the details.

![Screenshot_1675867840](https://user-images.githubusercontent.com/9727036/217564351-28ea9995-5a96-46d9-a550-7d0fc305776f.png)

### Steps to reproduce
1. Open app on Android.
2. Login to an account with transactions.
3. In the _Home_ tab, click on a transaction from the _Transactions Summary List_.
4. See that the _Parameters_ field doesn't contain the "_Expand_" button.

### Which version(s) does this affect? (Environment, OS, etc...)
Only Android.

**Comment by ManuGowda** [comment]
This issue is resolved as part of https://github.com/LiskHQ/lisk-mobile/issues/1645
@Balanced02 @ClementeSerrano please review the bug on iOS and android 🙏🏼
