### ISSUE TITLE
Tokens and transactions are not re-fetched when switching applications

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-mobile#1665]
### Expected behavior

- Should refetch tokens and transactions information when switching applications
 - Ensure to refetch token list on request token screen when application is changed
### Actual behavior

- Tokens and transactions are not re-fetched when switching applications

### Steps to reproduce

- Send or request the transaction
- Switch application
- Observe the information is not updated

### Which version(s) does this affect? (Environment, OS, etc...)
3.0

**Comment by soroushm** [comment]
perhaps chainId is not passing as key in react-query follow the same from desktop

**Comment by ClementeSerrano** [comment]
i think the issue is more that WS connection to automatically update the query is not working. Already tested, and the applications switching works good.

Should we change the title of the issue @ManuGowda ?

**Comment by ClementeSerrano** [comment]
closing because we discovered that was just that the WS URL configured on the `env` file was incorrect. No code intervention was required
