### ISSUE TITLE
Add loading skeleton for request token screen

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-mobile#1730]
### Description

The Request Token screen makes I/O requests that currently are being handled with a “Loading…“ plain text. We need to add Skeletons there to improve the UX.

### Motivation

- Improve user experience

### Additional Information

https://user-images.githubusercontent.com/6449871/227918300-437f251a-8eaa-4798-b83f-2ecc017718c1.mp4

**Comment by ClementeSerrano** [comment]
Done on https://github.com/LiskHQ/lisk-mobile/pull/1756
