### ISSUE TITLE
Merge screen 1 and 2 in send token

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1761]
### Description

Currently we have 4 steps to complete a token transfer

1. input recipient and to application
2. Input amount, token, message and review fee
3. summary
4. input password
5. success

As a mobile user the above steps are too many just to do a token transfer. Users should have minimal interaction for better user experience, hence we should merge the step 1 and 2 together.

**Comment by ClementeSerrano** [comment]
is this already merged? @Balanced02
