### ISSUE TITLE
Migrate users from v2 to v3

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1790]
### Description
Users from v2 should have a seamless transition to v3 by just adding an account password to their already existing account stored in the keychain

### Motivation
Seamless transition of users from v2 to v3

Please describe why it is needed
- Ensure users don't lost their passphrase stored on the keychain
- Ensure users have a seamless transition from v2 to v3

**Comment by ClementeSerrano** [comment]
Closing since #1803 was merged.
