### ISSUE TITLE
Remove hardcoded "message fee" from token:transfer form

### ISSUE THREAD

**Issue by ClementeSerrano** [LiskHQ/lisk-mobile#1799]
### Expected behavior
The "_message fee_" value in the token:transfer form should be fetched dynamically, based on the current fee structure, instead of using a hardcoded value.

### Actual behavior
The token:transfer form currently contains a hardcoded "message fee" value, which may not accurately represent the current fee structure.

### Steps to reproduce
1. Navigate to the token:transfer form in the app.
2. Select an account not initialised on the recipient application of the token transfer.
3. Observe the hardcoded "message fee" value in the form.

### Which version(s) does this affect? (Environment, OS, etc...)
All.

**Comment by ClementeSerrano** [comment]
This issue will be solved with https://github.com/LiskHQ/lisk-mobile/issues/1801

**Comment by ManuGowda** [comment]
Duplication https://github.com/LiskHQ/lisk-mobile/issues/1801
