### ISSUE TITLE
Follow design elements as proposed in Figma #1

### ISSUE THREAD

**Issue by Ade-kola** [LiskHQ/lisk-mobile#1852]
### Expected behavior

The app is expected to follow the design on the figma like the spacing, font sizes , colors e.t.c.

### Actual behavior

Some of the pages are looking a little off because they're not following the design on the figma file.

### Checklist of fixes
- [x] Adapt UI of "Wallet" screens according to official designs (0.5 SP).
- [x] Adapt UI of "Applications list" and "Application Details" screens according to official designs (1 SP, considering that new elements should be added).
- [x] Adapt UI of "Add account" screens according to official designs (3 SP, considering that new steps where added).
- [x] Adapt UI of "Bookmarks" screens according to official designs (1 SP, considering we need to handle accounts not initialised UI and search redesign).
- [ ] Adapt UI of "Settings" screens according to official designs (0.5 SP).
- [ ] Adapt UI of "Sign in" screens according to official designs (0.5 SP).
- [ ] Adapt UI of "User onboarding" screens (new and existing users) according to official designs (0.5 SP).
- [ ] Adapt UI of "Send token" form according to official designs (3 SP, considering adding the "Choose from bookmark" missing screen, select priority changes, and other missing components).
- [ ] Adapt UI of "Request token" screen according to official designs (0.5 SP).
- [ ] Adapt UI of "Wallet connections" screens according to official designs (1 SP, including transaction signing, new connection, connections list, among others).
- [ ] Adapt UI of common components (Modals, Inputs, Toast alerts, Tooltip modals, Switches, among others) according to official designs 3 SP).

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Comment by ClementeSerrano** [comment]
I would divide this issue in these multiple issues, according to each app module:

1. Adapt UI of "Sign in" screens according to official designs (0.5 SP).
2. Adapt UI of "User onboarding" screens (new and existing users) according to official designs (0.5 SP). 
3. Adapt UI of "Add account" screens according to official designs (3 SP, considering that new steps where added). 
4. Adapt UI of "Wallet" screens according to official designs (0.5 SP).
5. Adapt UI of "Send token" form according to official designs (3 SP, considering adding the "Choose from bookmark" missing screen, select priority changes, and other missing components).
6. Adapt UI of "Request token" screen according to official designs (0.5 SP).
7. Adapt UI of "Applications list" and  "Application Details" screens according to official designs (1 SP, considering that new elements should be added).
8. Adapt UI of "Wallet connections" screens according to official designs (1 SP, including transaction signing, new connection, connections list, among others).
9. Adapt UI of "Bookmarks" screens according to official designs (1 SP, considering we need to handle accounts not initialised UI and search redesign).
10. Adapt UI of "Settings" screens according to official designs (0.5 SP).
11. Adapt UI of common components (Modals, Inputs, Toast alerts, Tooltip modals, Switches, among others) according to official designs (2 SP).
