### ISSUE TITLE
Follow design elements as proposed in Figma #2

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-mobile#1905]
### Expected behavior

The app is expected to follow the design on the figma like the spacing, font sizes , colors e.t.c.

### Actual behavior

Some of the pages are looking a little off because they're not following the design on the figma file.

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Comment by ManuGowda** [comment]
All the necessary design changes where made, and the application has been submitted to review.
