### ISSUE TITLE
Click on the home button should scroll to the top of transactions

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#193]
### Description
When in the home page, after the user scrolls to bottom and loads a few sets of transactions, it's hard to scroll back to the top. In some applications, clicking on the home page in this situation scrolls to the top of the tap. This can be a useful functionality in our app too.

### Motivation
Make the user's life easier :-)

**Comment by aydieneue** [comment]
closed in #367 (forgot to add # to issue title)
