### ISSUE TITLE
Adapt UI of "Send token" form according to latest designs

### ISSUE THREAD

**Issue by ClementeSerrano** [LiskHQ/lisk-mobile#1950]
### Description

Update to the [latest designs](https://www.figma.com/file/jjuNNU9XxpeL57P25H1qri/Mobile-Prototype?type=design&node-id=1633-56997&mode=design&t=je3AxnAihlxkDLTs-4) the _Send token_ module UI elements.

Consider adding the "Choose from bookmark" missing screen, select priority changes, and other missing components.

### Motivation

The app is expected to be up-to-date on the designs specified by the product team.

**Comment by ManuGowda** [comment]
The current implementation is fulfilling all the needs of send token, hence closing this issue.
