### ISSUE TITLE
Adapt UI of "Request token" screen according to latest designs

### ISSUE THREAD

**Issue by ClementeSerrano** [LiskHQ/lisk-mobile#1951]
### Description

Update to the [latest designs](https://www.figma.com/file/jjuNNU9XxpeL57P25H1qri/Mobile-Prototype?type=design&node-id=1-14225&mode=design&t=je3AxnAihlxkDLTs-4) the _Request tokens_ module UI elements.

### Motivation

The app is expected to be up-to-date on the designs specified by the product team.

**Comment by ManuGowda** [comment]
Request token UI is implemented as expected.
