### ISSUE TITLE
Bump lisk-client version and remove patch

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-mobile#1996]
### Expected behavior
Should encrypt and decrypt account successfully without requiring any patch
Refer to the LIP changes to the protocol: https://github.com/LiskHQ/lips/pull/465/files

### Actual behavior
Uses patch-package to update lisk-client

### Tech Notes
- Remove `implementation 'com.lambdapioneer.argon2kt:argon2kt:1.3.0'` from the android build.gradle dependencies
- Remove `RNArgon2Module.jaba` and `RnArgon2Package.java`
- Remove the patch for lisk-client
- Remove hard-coded iterations, hashlength and memory size
- Remove and getKey options passed to encrypt and decrypt account functions

### Which version(s) does this affect? (Environment, OS, etc...)
- Android

**Comment by ManuGowda** [comment]
Address protocol changes: https://github.com/LiskHQ/lips/pull/465
