### ISSUE TITLE
The password screen behaves strangely.

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-mobile#2070]
### Expected behavior
The password screen behaves correctly.

### Actual behavior
behaves strangely.
- Position of the screen when it is closed and reopened.
- Screen shakes while typing

https://github.com/LiskHQ/lisk-mobile/assets/44485074/9b3c9eaf-6a7b-4be9-ade6-955dfae3c641

### Steps to reproduce
Enter password

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Mobile v3.0.0-rc.1
iPhone 14 pro
iOS 17.0.3

**Comment by ClementeSerrano** [comment]
Hi @lisknonanika ! Thanks for your issue.

Are you using a custom keyboard on your phone?

**Comment by lisknonanika** [comment]
Hi @ClementeSerrano 

No. I am using the default keyboard.
I thought it might be a language setting problem, so I changed it, but it is still the same.
Also, The same is true if the application is reinstalled or the device is rebooted.
