### ISSUE TITLE
Added application disappears after the restart

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-mobile#2128]
### Expected behavior
Blockchain application should be selectable after the wallet restart
### Actual behavior
After adding an application and restarting the wallet, user is unable to switch to the application.
### Steps to reproduce
Login to the mobile wallet on the current testnet, add Bloclite application, restart the wallet, try selecting the Bloclite application
### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Mobile 3.0.0-rc.3 ios

**Comment by ClementeSerrano** [comment]
Hi @przemerr , thanks for reporting this issue.

I'm trying to replicate it, but I can't. For me looks it's working properly.

I tested on iOS simulator and real device, plus Android emulator.

Can you please give us a bit more details about the context in which this is happening to you? 

Here I attach a proof of that is working on my hand:

https://github.com/LiskHQ/lisk-mobile/assets/9727036/a97faeec-8276-499a-bd2a-ff9b59efed68

**Comment by przemerr** [comment]
Hello @ClementeSerrano  it was testnet on an old iPhone 6s plus
and iPad Pro m1.. same behavior on both

https://github.com/LiskHQ/lisk-mobile/assets/25085095/010a01b0-e8c2-4f6d-93cf-ac3716b3f63f

**Comment by ManuGowda** [comment]
https://github.com/LiskHQ/lisk-mobile/assets/6449871/8e12946b-cabe-421e-a6d9-14fcc3c5e5b6

Its working for me on Android.

**Comment by ManuGowda** [comment]
@przemerr can you please check if can reproduce the issue with rc.4 version, and if you still find the issue reproducible please reopen?

**Comment by przemerr** [comment]
@ManuGowda Looks like I can't reproduce it on the v4 version 👍
