### ISSUE TITLE
Create the network switcher in Setting page

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#224]
We can implement a form to choose the network and in the case of "Custom node", define a URL to access the node. This can be placed on the setting page.
AS an inspiration, Lisk hub currently has a similar functionality on its setting page.

**Comment by reyraa** [comment]
Since we have implemented this feature using `env.json` file, there's no advantage to implement a UI for it. I close this issue.

**Comment by marijnbent** [comment]
I don't understand the reasoning behind closing this issue. At this moment, it is not possible to connect with the testnet as a user, right? I would like that functionality. It could be added under a new  'Advanced options' tab in settings.
