### ISSUE TITLE
Feature Request: Broadcasting offline signed transactions by scanning QR-codes

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-mobile#272]
Apps like [GDT Wallet](https://play.google.com/store/apps/details?id=mrv.liskgdt.wallet&hl=en) and [Lisk Mobile Broadcaster](https://play.google.com/store/apps/details?id=lisksnake.liskonlinebroadcaster2) are no longer allowed to release the new versions of their apps on Apple's app store. They offer the great feature to broadcast offline signed transactions. It would be awesome to have this feature on Lisk Mobile and therefore on Google's Play Store **and** Apple's App Store.

**Comment by reyraa** [comment]
We have discussed this feature Since it's useful only for less than 1% of the users, it's not in our priority list.
