### ISSUE TITLE
Rename "Lisk" to "Lisk Mobile" on app stores

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-mobile#274]
Why is the app just called "Lisk" on app stores? Shouldn't it be **Lisk Mobile**?

**Comment by reyraa** [comment]
@punkr0ck The project name is Lisk Mobile to comply with the naming convention in LiskHQ repositories. but the App is distributed under the simple _Lisk_ title to make it easier pronounced.
