### ISSUE TITLE
Use standard Android UI Elements like the "App Bar", Navigation, Swiping features, etc...

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-mobile#275]
Mobile apps should respect the standard elements, functions and ui elements of their os. People are used to their mobile os and how apps (should) feel and work.
I know only the Android world (can't talk about IOS). Lisk Mobile looks nice, but it doesn't feel (yet) like a regular Android app, because it does not use the standard ui elements like for example the "App Bar", a regular Navigation, supported swiping gestures, etc...

A good starting point for such things is here:
https://developer.android.com/guide/topics/ui/

**Comment by reyraa** [comment]
@simonmorgenthaler Thank you for the suggestion. We'll consider this in our the versions.
would be helpful if you created a list of potential behaviors you would consider "not Android like".

**Comment by simonmorgenthaler** [comment]
* I'd like to have that "App Bar" on top, with a menu on the left side that contains the "Settings", "About", and future features, and which can be swiped in from the side.
* A lot of the info (especially on the "Transaction details" page are not real text and can not be copy/pasted. Everything should be regular text that can be marked and copy/pasted.
* The "Share" feature can be useful sometimes, but I'd prefer it working only on the "share" icon, not on the complete Account number. 99% of the time I want to copy/paste the account number and not "share" it with anyone or any app.
* The main categories Wallet, Send, Request, could be switched using swipe gestures.
