### ISSUE TITLE
Create tasks in a background thread (service) to push notification when the balance changed

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#299]
### Description
The title is pretty much explanatory. This [article](https://hackernoon.com/easy-os-background-tasks-in-react-native-bc4476c48b8a) can be helpful.

### Motivation
To push notifications when the balance changed.

### Requirements
#297 
#298

**Comment by wyh136** [comment]
please dont push notification when the account got forged reward.
