### ISSUE TITLE
Open the account page by entering the address instead of the passphrase 

### ISSUE THREAD

**Issue by tomploem** [LiskHQ/lisk-mobile#310]
### Description
A user should have the option to enter a passphrase or just the address. Entering a address instead of a passphrase lets the user monitor the account without having the interaction such as creating a transaction. 

### Motivation
As a delegate i want to monitor my voters by having an up-to-date overview. It is very important for me that the passphrase is only entered in a controlled environment so using the application as a monitoring tool would vastly improve having that overview in my pocket without going to the explorer.

### Requirements
- Open the application and have the choice of entering the passphrase or just your address

**Comment by reyraa** [comment]
Thank you for your feature request. We want this application to target investors and that means:
 - It should be easy to use.
 - It should include features useful for all the users.

Based on our user testing results, unfortunately, this feature along with passphrase is very confusing for most users.
Hence, at the moment this is not a part of our development roadmap.
