### ISSUE TITLE
Implement login using Password

### ISSUE THREAD

**Issue by benfavre** [LiskHQ/lisk-mobile#369]
### Description
Implement login using a simple password.

### Motivation
The user should only have to type the private key once and we can store it encrypted on the phone.
This Bitcoin wallet in ReactNative could give you an example implementation: https://github.com/BlueWallet/BlueWallet

### Requirements
Only type private key once
Provide an alternative to TouchID for older phones (probably more secure than a fingerprint anyway)

### Am I planning to do it myself with a PR?
No.

**Comment by reyraa** [comment]
We have decided to use the BIP39 passphrase instead of the user-defined passwords for security reasons. Since short passphrases are not strong against [Brute force attack](https://en.wikipedia.org/wiki/Brute-force_attack), we will not introduce this feature.
