### ISSUE TITLE
Validate all inputs on submit and remove the disabled state

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#423]
The following inputs must be validated after the form is submitted and the potential error messages must hide after the user started editing the value:
 - Passphrase in sign in screen.
 - Passphrase in second passphrase screen.
 - The Amount input in Send screen.
 - The address input in Send and Request screens.
 

The following input must be validated on input change and show/hide the error messages right away:
 - Reference field in Send screen.

**Comment by aydieneue** [comment]
Note: part of this has been done on https://github.com/LiskHQ/lisk-mobile/commit/db533e604293d29cfb5cfea6cf58e726d3b6d158
