### ISSUE TITLE
Is there a java API lib for Lisk?

### ISSUE THREAD

**Issue by stjordanis** [LiskHQ/lisk-mobile#463]
A java api lib would make integration of LISK easier for coinomi, our lightweight mobile multi asset wallet app.  I wonder if we can reuse or get help from code in java libs of ARK, such as:

java-client/src at master · ArkEcosystem/java-client
https://github.com/ArkEcosystem/java-client/tree/master/src

ArkEcosystem/java-client: A simple Java API client for the ARK Blockchain.
https://github.com/ArkEcosystem/java-client

**Comment by reyraa** [comment]
Unfortunately, at the moment, we don't have a Java API lib for Lisk. We've have discussed this, it's not in our current list of priorities. but we'll provide API libs for other languages in the future.
