### ISSUE TITLE
Investigate building iMessage extension with native code

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#539]
We would like to create an iMessage plugin using swift which enables users to request tokens from their contacts and respond to incoming requests.

Since the main application is in React Native and Lisk, in general, is a JS-based platform, that would be our preferred language, but if writing the plugin in native language helps improve the performance remarkably, we will consider using the native plugin.

This ticket works in conjunction with #540

**Comment by aydieneue** [comment]
After some investigation and experimentation, we decided to go with a hybrid solution (iMessage API bridge with Swift + UI with React Native) which can be tracked on #542
