### ISSUE TITLE
Improve developer experience of the iMessage bridge

### ISSUE THREAD

**Issue by altaywtf** [LiskHQ/lisk-mobile#552]
### Description
- [x] Fix event listeners on reload https://github.com/LiskHQ/lisk-mobile/pull/559/commits/f07d4d797dc1996f78afc0cb07b096a28a2b6bff
- [ ] Display React Native Redbox when there's a crash on the JS side.
- [ ] Add a keyboard shortcut / intractable element for reloading the app, in case of crash.
- [x] Investigate opening remote debugger https://github.com/LiskHQ/lisk-mobile/commit/0ff5f454b990e3f14e3cd686155f850abf408783
- [ ] Investigate about providing a better image loading solution
- [x] Provide helper methods for managing launchScreen. https://github.com/LiskHQ/lisk-mobile/pull/573

### Motivation
To enhance the DX of iMessage extension and make it more easy to use.

**Comment by ManuGowda** [comment]
iMessage feature is deactivated at the moment, for now we can consider this issue as closed, when we decided to activate the iMessage, we will create objectives to work on them.

**Comment by ManuGowda** [comment]
We decided not to implement this feature as we have other means to achieve the same.
