### ISSUE TITLE
Structure the common test data

### ISSUE THREAD

**Issue by altaywtf** [LiskHQ/lisk-mobile#645]
### Description

The current state of our test files is a little bit messy in terms of using the fixtures. In order to avoid repetition and have a well-defined example dataset, it'd be nice to invest some time on refactoring our tests.

### Motivation
- Decrease repetition
- Use a more structured and accurate example data
- Increase the speed of adding new tests to the codebase

**Comment by ManuGowda** [comment]
This has been addressed in the source code e.g https://github.com/LiskHQ/lisk-mobile/tree/development/src/modules/Transactions/__fixtures__
