### ISSUE TITLE
Implement the new no-network template in home

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#749]
When the network is down, the user can sign in (considering signing in is an offline process). but the application won't be able to fetch the account details and the list of transactions.
In this situation we ned to show an illustrations and an explaining message.
Find the design in [InVision](https://projects.invisionapp.com/d/main#/console/17093670/354341348/preview).

### Acceptance criteria 
 - Check the connection every 30 sec.
 - If the connection if off, show the error message.
 - Don't show the message again after 30 sec if the internet connection was still off.
 - Show this error message if user tried to send tokens while there's no connection.

**Comment by colado** [comment]
Closing this issue since its sprint expired weeks ago. The [QA changes needed](https://github.com/LiskHQ/lisk-mobile/issues/749#issuecomment-535983491) will be implemented on #993
