### ISSUE TITLE
The pending BTC transaction states "Invalid date" instead of "Pending confirmation"

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#772]
### How to reproduce
 - Activate BTC in home page.
 - Send a transaction to your BTC address from another client.

### Expected behaviour
 - The pending transaction should be added as soon as it's in the node pool.
 - The transaction in the tx list in home page should say "Pending confirmation" under the address.
 - The balance should not reflect the value of the transaction.

after the first confirmation
 - The tx date/time should replace the "Pending confirmation" subtitle.
 - The balance must be updated.

### Actual behaviour
 - The tx subtitle says "Invalid date" and stays the same even after the first confirmation.
 - The balance doesn't get updated.

**Comment by aydieneue** [comment]
This is fixed with the changes in https://github.com/LiskHQ/lisk-mobile/pull/741 and https://github.com/LiskHQ/lisk-mobile/pull/776 👌
