### ISSUE TITLE
Discreet mode visual feedback

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-mobile#830]
Just like in Desktop, users can choose to select discrete mode while tries to sign-in to an account. We need to support this on mobile so users don’t have to get into an account before toggling discrete mode.

This is for security when users tries to access their account in a public space/

**Comment by reyraa** [comment]
This is a good idea with clear benefit for users. Thank you @JesusTheHun . I'll plan this for our upcoming version.
