### ISSUE TITLE
Second Passphrase not work on BTC wallet

### ISSUE THREAD

**Issue by hitobb** [LiskHQ/lisk-mobile#910]
### Hardware Spec

 - [x] Android
    - Version 9
 - [x] iOS
    - Version 12.2

### How to reproduce

1. Sign in with Lisk account with second passphrase enabled
2. Switch to BTC wallet
3. Send BTC
4. I can send BTC without input second passphrase

### Expected behaviour

Second Passphrase should work on BTC wallet

### Actual behaviour

Second Passphrase not work on BTC wallet

### Other

This behavior has been verified in the following versions.

- Lisk mobile Version 1.2.0

**Comment by reyraa** [comment]
@hitobb Thank you for reaching out. Second passphrase is a Lisk specific feature. Bitcoin doesn't support it. This is not a bug, it's a difference between Lisk and Bitcoin blockchains.

**Comment by hitobb** [comment]
I understood it was the expected behavior.
Thank you for the explanation.
