### ISSUE TITLE
Account initialization modal only works with the first uninitialized account

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-mobile#923]
### How to reproduce
If you sign in using a non-initialized account and dismiss the initialization modal, the dismissal is saved. and if you sign in with another non-initialized account, this modal is not shown.

### Actual behavior
The initialization modal is not shown if you had dismiss it before for another account.

### Expected behavior
We should show the modal for any uninitialized account at any time.

**Comment by colado** [comment]
Closing this issue as the bug is not reproducible and current implementation is correct.
