### ISSUE TITLE
Send: Scan button doesn't open scanner if keyboard was opened

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-mobile#930]
### How to reproduce
1. Open send screen
1. Click inside the search filter to open keyboard
1. Click send button

### Actual behaviour
Keyboard closes. 
You need to click one more time to start the scanner.

### Expected behaviour
Keyboard closes and scanner starts

**Comment by colado** [comment]
The issue has been suspended and postponed for a future sprint.
