### ISSUE TITLE
Signature deeplink

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-mobile#955]
Scenario : I would like to use third party apps, but there is no way I share my passphrase with them.
A third party app should be able to call a deep link to sign a transaction:

`lisk://sign?transaction=<transactionJSON>&callback=thirdPartyApp://signatureCallback`

This way I can sign using Lisk Mobile, and the third party app can send the signed transaction without having to use it.

I'm willing to write the PR if you are ok with this proposal.

**Comment by yasharAyari** [comment]
Your idea looks very interesting. Can you please make more example use case that you want to achieve with this feature.

**Comment by JesusTheHun** [comment]
It's pretty much like an OAuth2 flow.
I want to be able to use a trusted app - Lisk Mobile from LiskHQ - to be able to sign third party app's transactions.

Let's say I have an app called "MySuperApp" with in-app purchases. I want to integrate Lisk as a way of payment. I offer the user a button to click, when clicked the user is redirected in the Lisk Mobile app to sign the transaction -which includes all the metadata the app need to track the payment-, once signed and eventually broadcasted, he comes back to MySuperApp, we watch until the transaction is confirmed, and we're done !

This also set a foot into Lisk Mobile being a generic wallet for all Lisk DApps.

**Comment by ClementeSerrano** [comment]
Hi @JesusTheHun , we are solving this issue on https://github.com/LiskHQ/lisk-mobile/pull/1520 , with some slightly changes to what you propose.

The deep link to connect to Lisk wallet is going to be `lisk://wallet`, and the first implementation will be for the *Send token* feature.

This deep link will accept the following query params:

- `recipientAddress`: LSK address of the recipient of the send token transaction
- `recipientApplicationChainID`: Blockchain application chain ID to where the tokens are going to be sent on the transaction.
- `recipientTokenID`: Token ID of the token being sent.
- `amount`: Amount (in Beddows) to send.
- `message`: Optional message attached to the transaction.

An example of deep link could be:

```
lisk://wallet?recipientAddress=lske5sqed53fdcs4m9et28f2k7u9fk6hno9bauday&recipientApplicationChainID=04000000&recipientTokenID=0000000000000000&amount=1000000000
```
